# Generated by Django 4.2.11 on 2024-04-10 22:41

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('type', models.CharField(max_length=40)),
                ('addToGallery', models.IntegerField(default=0)),
                ('annotations', models.TextField(default='', max_length=1000)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SegmentedImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('annotations', models.TextField(default='', max_length=1000)),
                ('generatedImageId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gennotate.generatedimage')),
            ],
        ),
    ]
